
      - name: Build Debug APK
        working-directory: ./skaes-android
        run: gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SKAES-Distribusiku-APK
          path: skaes-android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
